#!/bin/bash

# This file is part of the Soletta Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

COMPILE_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
SOLETTA_TARGET=$COMPILE_DIR/soletta-target/build/soletta_sysroot
source $COMPILE_DIR/common-compile.sh

mkdir -p output-tree/usr/bin

gcc -Werror -Wall -o output-tree/usr/bin/app -I. -I$SOLETTA_TARGET/usr/include/soletta -L$SOLETTA_TARGET/usr/lib -lsoletta $(find -name '*.c')

if [ $? -ne 0 ]; then
    exit 1
fi

IMAGE=$PLATFORM_NAME.img

cp $COMPILE_DIR/base.img $IMAGE

################################################################
############ TODO: how to get rid of this 'sudo' ###############
################################################################
sudo $COMPILE_DIR/copy-tree-to-linux-image.sh $IMAGE output-tree

zip output.zip $IMAGE
rm $IMAGE
