#!/bin/bash

# This file is part of the Soletta Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

COMPILE_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
SOLETTA_TARGET=$COMPILE_DIR/contiki/external_lib/soletta/soletta/build/soletta_sysroot
source $COMPILE_DIR/common-compile.sh

for dir in `find -type d`; do
    mkdir -p obj_native/$dir
done

cat > Makefile <<EOF
CONTIKI_PROJECT = main
USE_EXT_LIBS += soletta

all: \$(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += $(find -name '*.c' | grep -v main.c | tr '\n' ' ')

CONTIKI = $COMPILE_DIR/contiki
include \$(CONTIKI)/Makefile.include
EOF

make V=1

if [ $? -ne 0 ]; then
    exit 1
fi

zip output.zip main.native
