#!/bin/bash

# This file is part of the Soletta Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PREPARE_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
source $PREPARE_DIR/../common/common-prepare.sh

cd $COMPILE_DIR

if [[ -n $CONTIKI_REPO ]]; then
    git clone $CONTIKI_REPO
else
    echo "Cannot clone Contiki. Please, set CONTIKI_REPO variable."
    exit 1
fi

cd contiki
git checkout soletta-port

cp $PREPARE_DIR/Makefile.soletta ./external_lib/soletta/Makefile

cd examples/soletta-gpio-example
make

cp \
    $PREPARE_DIR/compile \
    $PREPARE_DIR/../common/common-compile.sh \
    $COMPILE_DIR

chmod +x $COMPILE_DIR/compile
