#!/bin/bash

# This file is part of the Soletta Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

COMPILE_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
SOLETTA_TARGET=$COMPILE_DIR/RIOT/pkg/libsoletta/soletta/build/soletta_sysroot
source $COMPILE_DIR/common-compile.sh
source $COMPILE_DIR/common-arduino-compile.sh

cp \
    $COMPILE_DIR/RIOT/examples/soletta_app/bin/arduino-due/soletta_app.hex \
    $COMPILE_DIR/RIOT/boards/arduino-due/dist/* \
    $COMPILE_DIR/flash.sh \
    $PLATFORM_NAME

zip -r output.zip $PLATFORM_NAME
rm -rf $PLATFORM_NAME
