#!/bin/bash

# This file is part of the Soletta Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO: Prepare script should handle this automatically.

PREPARE_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))

source $PREPARE_DIR/../common/common-prepare.sh

####################### TODO ##########################
# Clone soletta-target as we do for the other platforms
# and compile it with the toolchain provided by
# Barbieri's SDK (i586-quark-linux-musl). Replace the
# libsoletta.a within the SDK by the generated one.
#######################################################

if [[ -n $BASE_IMAGE_URL ]]; then
    wget "$BASE_IMAGE_URL/base.img" -P $PREPARE_DIR
else
    echo "Could not download base.img. Please, set BASE_IMAGE_URL variable."
    exit 1
fi

which i586-quark-linux-musl-gcc

if [ $? -ne 0 ]; then
    echo "
          Cross compiler not found. Please install SDK: 
          solda-intel-galileo-gen2-soletta-master.tar.bz2
         "
    exit 1
fi

cp \
    $PREPARE_DIR/../common/common-compile.sh \
    $PREPARE_DIR/compile \
    $PREPARE_DIR/base.img \
    $PREPARE_DIR/flash.sh \
    $COMPILE_DIR

cp -r \
    $PREPARE_DIR/opt \
    $COMPILE_DIR

chmod +x $COMPILE_DIR/compile
chmod +x $COMPILE_DIR/flash.sh

rm -rf $PREPARE_DIR/opt*
