#!/bin/bash

# This file is part of the Soletta Project
#
# Copyright (C) 2015 Intel Corporation. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PREPARE_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
source $PREPARE_DIR/../common/common-prepare.sh

pushd $COMPILE_DIR

git clone --dissociate --reference $COMPILE_DIR/soletta-host https://github.com/solettaproject/soletta.git soletta-target

pushd soletta-target

make alldefconfig

make -j $PARALLEL_JOBS

if [ $? -ne 0 ]; then
    exit 1
fi

cp \
   $PREPARE_DIR/compile \
   $COMPILE_DIR

# Make it easy to develop common-compile.sh
ln -s $PREPARE_DIR/../common/common-compile.sh $COMPILE_DIR

chmod +x $COMPILE_DIR/compile
